# Generated by Django 4.1.2 on 2022-10-28 05:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wrcsystem', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RaspberryPi_Name', models.CharField(max_length=16)),
                ('celsius', models.FloatField()),
                ('fahrenheit', models.FloatField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
