# Generated by Django 4.1.2 on 2022-11-10 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrcsystem', '0004_alter_watertemperature_celsius_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapDanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=16)),
                ('risk', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='危険度')),
                ('map_images', models.ImageField(upload_to='map_pics')),
            ],
        ),
    ]
