# Generated by Django 4.1.2 on 2022-11-16 05:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrcsystem', '0006_waterhigh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterhigh',
            name='high',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='水位'),
        ),
        migrations.AlterField(
            model_name='watertemperature',
            name='celsius',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='摂氏温度'),
        ),
        migrations.AlterField(
            model_name='watertemperature',
            name='fahrenheit',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='華氏温度'),
        ),
    ]
