# Generated by Django 4.1.2 on 2023-01-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrcsystem', '0008_remove_account_account_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WaterHigh',
            new_name='OldWaterHigh',
        ),
        migrations.RenameModel(
            old_name='WaterTemperature',
            new_name='OldWaterTemperature',
        ),
    ]
