# Generated by Django 4.1.2 on 2023-01-20 04:21

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wrcsystem', '0009_rename_waterhigh_oldwaterhigh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WRCSAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ras_id', models.IntegerField(default=-1)),
                ('ras_point', models.CharField(default='No Point', max_length=16)),
                ('OutWater_flg', models.BooleanField(default=False, help_text='散水中ならTrue', null=True)),
                ('InputWater_flg', models.BooleanField(default=False, help_text='吸水中ならTrue', null=True)),
                ('water_level', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('water_level_flg', models.BooleanField(default=False, help_text='貯水量50%以上ならTrue', null=True)),
                ('water_temperature', models.DecimalField(decimal_places=3, default=0, max_digits=5, null=True)),
                ('ground_altitude', models.DecimalField(decimal_places=3, default=0, max_digits=5, null=True)),
            ],
        ),
    ]
