# Generated by Django 4.1.2 on 2023-01-20 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrcsystem', '0010_wrcsall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wrcsall',
            old_name='InputWater_flg',
            new_name='InWater_flg',
        ),
    ]
