# Generated by Django 4.1.2 on 2022-12-21 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WRCS_sumple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RaspberryPi_ID', models.IntegerField(unique=True)),
                ('RaspberryPi_point', models.CharField(max_length=16)),
                ('water_high', models.DecimalField(decimal_places=3, max_digits=6)),
                ('water_temperature', models.DecimalField(decimal_places=3, max_digits=5)),
                ('is_water_out', models.BooleanField(default=False)),
                ('is_water_in', models.BooleanField(default=False)),
                ('altitude', models.DecimalField(decimal_places=3, max_digits=5)),
                ('now_weather', models.CharField(max_length=8)),
                ('future_weather', models.CharField(max_length=8)),
                ('now_temperature', models.DecimalField(decimal_places=3, max_digits=5)),
                ('future_temperature', models.DecimalField(decimal_places=3, max_digits=5)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='SurveyTest',
        ),
    ]
