# Generated by Django 4.1.2 on 2022-12-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_wrcs_sumple_raspberrypi_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebLayoutQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.IntegerField(unique=True)),
                ('question_first_sumple1', models.BooleanField()),
                ('question_first_sumple2', models.BooleanField()),
                ('question_first_sumple3', models.BooleanField()),
                ('question_second', models.IntegerField()),
                ('question_third_sumple1', models.BooleanField()),
                ('question_third_sumple2', models.BooleanField()),
                ('question_third_sumple3', models.BooleanField()),
                ('question_fourth', models.IntegerField()),
                ('question_fifth', models.BooleanField()),
                ('question_sixth_date', models.BooleanField()),
                ('question_sixth_RaspberryPi_ID', models.BooleanField()),
                ('question_sixth_RaspberryPi_point', models.BooleanField()),
                ('question_sixth_is_water_out', models.BooleanField()),
                ('question_sixth_is_water_in', models.BooleanField()),
                ('question_sixth_water_high', models.BooleanField()),
                ('question_sixth_water_temperature', models.BooleanField()),
                ('question_sixth_altitude', models.BooleanField()),
                ('question_sixth_now_weather', models.BooleanField()),
                ('question_sixth_future_weather', models.BooleanField()),
                ('question_sixth_now_temperature', models.BooleanField()),
                ('question_sixth_future_temperature', models.BooleanField()),
                ('question_seventh', models.BooleanField()),
                ('question_eighth_date', models.BooleanField()),
                ('question_eighth_RaspberryPi_ID', models.BooleanField()),
                ('question_eighth_water_high', models.BooleanField()),
                ('question_eighth_water_temperature', models.BooleanField()),
                ('question_eighth_altitude', models.BooleanField()),
                ('question_eighth_now_temperature', models.BooleanField()),
                ('question_eighth_future_temperature', models.BooleanField()),
                ('question_ninth', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='WRCS_sumple',
            new_name='WRCS_sample',
        ),
    ]
