# Generated by Django 4.1.2 on 2022-12-21 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_weblayoutquestion_rename_wrcs_sumple_wrcs_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebLayoutQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.IntegerField(unique=True)),
                ('question_first_sumple1', models.BooleanField()),
                ('question_first_sumple2', models.BooleanField()),
                ('question_first_sumple3', models.BooleanField()),
                ('question_second', models.IntegerField()),
                ('question_third_sumple1', models.BooleanField()),
                ('question_third_sumple2', models.BooleanField()),
                ('question_third_sumple3', models.BooleanField()),
                ('question_fourth', models.IntegerField()),
                ('question_fifth', models.BooleanField()),
                ('question_sixth_date', models.BooleanField()),
                ('question_sixth_RaspberryPi_ID', models.BooleanField()),
                ('question_sixth_RaspberryPi_point', models.BooleanField()),
                ('question_sixth_is_water_out', models.BooleanField()),
                ('question_sixth_is_water_in', models.BooleanField()),
                ('question_sixth_water_high', models.BooleanField()),
                ('question_sixth_water_temperature', models.BooleanField()),
                ('question_sixth_altitude', models.BooleanField()),
                ('question_sixth_now_weather', models.BooleanField()),
                ('question_sixth_future_weather', models.BooleanField()),
                ('question_sixth_now_temperature', models.BooleanField()),
                ('question_sixth_future_temperature', models.BooleanField()),
                ('question_seventh', models.BooleanField()),
                ('question_eighth_date', models.BooleanField()),
                ('question_eighth_RaspberryPi_ID', models.BooleanField()),
                ('question_eighth_water_high', models.BooleanField()),
                ('question_eighth_water_temperature', models.BooleanField()),
                ('question_eighth_altitude', models.BooleanField()),
                ('question_eighth_now_temperature', models.BooleanField()),
                ('question_eighth_future_temperature', models.BooleanField()),
                ('question_ninth', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WRCS_samples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RaspberryPi_ID', models.IntegerField()),
                ('RaspberryPi_point', models.CharField(max_length=16)),
                ('water_high', models.DecimalField(decimal_places=3, max_digits=6)),
                ('water_temperature', models.DecimalField(decimal_places=3, max_digits=5)),
                ('is_water_out', models.BooleanField(default=False)),
                ('is_water_in', models.BooleanField(default=False)),
                ('altitude', models.DecimalField(decimal_places=3, max_digits=5)),
                ('now_weather', models.CharField(max_length=8)),
                ('future_weather', models.CharField(max_length=8)),
                ('now_temperature', models.DecimalField(decimal_places=3, max_digits=5)),
                ('future_temperature', models.DecimalField(decimal_places=3, max_digits=5)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='WebLayoutQuestion',
        ),
        migrations.DeleteModel(
            name='WRCS_sample',
        ),
    ]
