# Generated by Django 4.1.2 on 2022-12-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_weblayoutquestions_wrcs_samples_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_eighth_RaspberryPi_ID',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_eighth_altitude',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_eighth_date',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_eighth_future_temperature',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_eighth_now_temperature',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_eighth_water_high',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_eighth_water_temperature',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_fifth',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_first_sumple1',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_first_sumple2',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_first_sumple3',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_fourth',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_ninth',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_second',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_seventh',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_sixth_RaspberryPi_ID',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_sixth_RaspberryPi_point',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_sixth_altitude',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_sixth_date',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_sixth_future_temperature',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_sixth_future_weather',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_sixth_is_water_in',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_sixth_is_water_out',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_sixth_now_temperature',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_sixth_now_weather',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_sixth_water_high',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_sixth_water_temperature',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_third_sumple1',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_third_sumple2',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_third_sumple3',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='student_number',
            field=models.IntegerField(null=True, unique=True, verbose_name='学籍番号'),
        ),
    ]
