# Generated by Django 4.1.2 on 2022-12-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_alter_weblayoutquestions_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='question_ninth',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='weblayoutquestions',
            name='student_number',
            field=models.IntegerField(unique=True),
        ),
    ]
